import { useState, useRef, useEffect } from "react";
import { Send, Loader2, Sparkles, User, Bot } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Card } from "@/components/ui/card";
import { useChat } from "@/contexts/ChatContext";
import { ApiService } from "@/services/api";
import type { Message } from "@/types";
import { cn } from "@/lib/utils";

export function ChatPanel() {
  const { currentSession, addMessage, updateLastMessage, setCurrentSessionId } =
    useChat();
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Auto-scroll to bottom when messages change
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [currentSession?.messages]);

  // Focus textarea on session change
  useEffect(() => {
    textareaRef.current?.focus();
  }, [currentSession?.id]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isLoading || !currentSession) return;

    const userMessage: Message = {
      id: crypto.randomUUID(),
      role: "user",
      content: input.trim(),
      timestamp: Date.now(),
    };

    addMessage(userMessage);
    setInput("");
    setIsLoading(true);

    // Create assistant message placeholder
    const assistantMessage: Message = {
      id: crypto.randomUUID(),
      role: "assistant",
      content: "",
      timestamp: Date.now(),
    };
    addMessage(assistantMessage);

    // Prepare messages for API (exclude empty assistant messages)
    const apiMessages = [...currentSession.messages, userMessage]
      .filter(
        (msg) =>
          msg.role === "user" ||
          (msg.role === "assistant" && msg.content.trim()),
      )
      .map((msg) => ({
        role: msg.role,
        content: msg.content,
      }));

    try {
      // Determine session ID for API call
      // For new sessions (generated by frontend), send null to let backend create one
      const backendSessionId =
        currentSession.messages.length === 0 ? null : currentSession.id;

      // Use streaming API
      await ApiService.sendMessageStream(
        backendSessionId,
        apiMessages,
        // onChunk
        (content) => {
          updateLastMessage(content);
        },
        // onComplete
        (sessionId) => {
          if (sessionId && sessionId !== currentSession.id) {
            // Update session with backend-generated ID
            setCurrentSessionId(sessionId);
          }
          setIsLoading(false);
        },
        // onError
        (error) => {
          console.error("Error sending message:", error);
          // Update last message with error
          updateLastMessage(`\n\n[Error: ${error.message}]`);
          setIsLoading(false);
        },
      );
    } catch (error) {
      console.error("Error sending message:", error);
      setIsLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit(e);
    }
  };

  if (!currentSession) {
    return (
      <div className="flex h-full items-center justify-center bg-background">
        <div className="text-center max-w-md">
          <div className="mb-6 inline-flex items-center justify-center w-20 h-20 rounded-2xl bg-primary shadow-lg">
            <Sparkles className="w-10 h-10 text-primary-foreground" />
          </div>
          <h3 className="text-2xl font-semibold text-primary mb-3">
            Welcome to Kode Agent Chat
          </h3>
          <p className="text-sm text-muted-foreground">
            Create a new chat to get started with your AI assistant
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-full flex-col bg-background">
      {/* Header */}
      <div className="border-b border-border p-4 bg-card shadow-sm">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-primary flex items-center justify-center shadow-lg">
            <Sparkles className="w-5 h-5 text-primary-foreground" />
          </div>
          <div>
            <h2 className="font-semibold text-primary">
              {currentSession.title}
            </h2>
            <p className="text-xs text-muted-foreground">
              {currentSession.messages.length} messages
            </p>
          </div>
        </div>
      </div>

      {/* Messages */}
      <ScrollArea className="flex-1 p-4 bg-background" ref={scrollRef}>
        <div className="space-y-4">
          {currentSession.messages.length === 0 ? (
            <div className="flex h-full items-center justify-center text-muted-foreground">
              <div className="text-center">
                <Bot className="w-12 h-12 mx-auto mb-3 opacity-50" />
                <p className="text-sm">Start a conversation...</p>
              </div>
            </div>
          ) : (
            currentSession.messages.map((message) => (
              <div
                key={message.id}
                className={cn(
                  "flex gap-3",
                  message.role === "user" ? "justify-end" : "justify-start",
                )}
              >
                {message.role === "assistant" && (
                  <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center shrink-0 shadow-md">
                    <Bot className="w-4 h-4 text-primary-foreground" />
                  </div>
                )}
                <Card
                  className={cn(
                    "max-w-[70%] p-4 shadow-sm",
                    message.role === "user"
                      ? "bg-primary text-primary-foreground rounded-2xl rounded-tr-sm"
                      : "bg-card border border-border rounded-2xl rounded-tl-sm",
                  )}
                >
                  <div className="whitespace-pre-wrap break-words text-sm">
                    {message.content}
                  </div>
                  <div
                    className={cn(
                      "mt-2 text-xs",
                      message.role === "user"
                        ? "text-primary-foreground/70"
                        : "text-muted-foreground",
                    )}
                  >
                    {new Date(message.timestamp).toLocaleTimeString()}
                  </div>
                </Card>
                {message.role === "user" && (
                  <div className="w-8 h-8 rounded-lg bg-accent flex items-center justify-center shrink-0 shadow-md">
                    <User className="w-4 h-4 text-primary" />
                  </div>
                )}
              </div>
            ))
          )}
          {isLoading && (
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center shrink-0 shadow-md">
                <Bot className="w-4 h-4 text-primary-foreground" />
              </div>
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <Loader2 className="h-4 w-4 animate-spin" />
                <span>Thinking...</span>
              </div>
            </div>
          )}
        </div>
      </ScrollArea>

      {/* Input */}
      <div className="border-t border-border p-4 bg-card">
        <form onSubmit={handleSubmit} className="flex gap-3">
          <Textarea
            ref={textareaRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Type your message... (Shift+Enter for new line)"
            className="min-h-[60px] max-h-[200px] resize-none bg-background border-border"
            disabled={isLoading}
          />
          <Button
            type="submit"
            size="icon"
            disabled={!input.trim() || isLoading}
            className="h-[60px] w-[60px] shrink-0 rounded-xl shadow-lg"
          >
            {isLoading ? (
              <Loader2 className="h-5 w-5 animate-spin" />
            ) : (
              <Send className="h-5 w-5" />
            )}
          </Button>
        </form>
      </div>
    </div>
  );
}
